### ISSUE TITLE
irafutils cannot decode ascii in Python 3

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stsci.tools#11] opened 2016-10-31 15:28 UTC
Python 3 incompatibility causes traceback below, as reported by Zhixin Peng from School of Astronomy and Space Science, Nanjing University, China:

```
--> displ m92v.fits
frame to be written into (1:16) (1):
z1=488. z2=611.9556
--> imexam
Traceback (innermost last):
  File "<CL script CL1>", line 1, in <module>
    iraf.imexam(_save=1)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/stsci/tools/irafutils.py", line 402, in tkread
    return _TkRead().read(file, n)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/stsci/tools/irafutils.py", line 482, in read
    self.widget.mainloop()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/tkinter/__init__.py", line 1120, in mainloop
    self.tk.mainloop(n)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/stsci/tools/irafutils.py", line 495, in _read
    if PY3K: snew = snew.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0x95 in position 41: ordinal not in range(128)
```

See Footprints Ticket 9446.

**Comment by lupinix** [comment] 2016-12-05 17:26
Hi, I'm getting the same issue (Fedora 25, Python 3.5, stsci.tools 3.4.2.1, pyraf 2.1.13)

`PyRAF 2.1.13 Copyright (c) 2002 AURA
Python 3.5.2 Copyright (c) 2001-2016 Python Software Foundation.
Python/CL command line wrapper
  .help describes executive commands
--> !ds9 &
--> display /astro-data/Messdaten/2016_12_04_Rx_And/Light/V/Rx_And_Light_001.fits
frame to be written into (1:16) (1): 1
z1=921.6367 z2=1771.214
--> imexamine
Traceback (innermost last):
  File "<CL script CL1>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/stsci/tools/irafutils.py", line 409, in tkread
    return _TkRead().read(file, n)
  File "/usr/lib/python3.5/site-packages/stsci/tools/irafutils.py", line 489, in read
    self.widget.mainloop()
  File "/usr/lib64/python3.5/tkinter/__init__.py", line 1131, in mainloop
    self.tk.mainloop(n)
  File "/usr/lib/python3.5/site-packages/stsci/tools/irafutils.py", line 502, in _read
    if PY3K: snew = snew.decode('ascii')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xb8 in position 32: ordinal not in range(128)`

**Comment by pllim** [comment] 2016-12-05 17:28
@lupinix , if `imexam` is the only reason you are using PyRAF when you encounter this error, it is best to switch to the Python implementation of `imexam` (see http://imexam.readthedocs.io/en/latest/).

**Comment by lupinix** [comment] 2016-12-05 17:30
@pllim We are using PyRAF in general for analysis of our data as it is the best and most comfortable way to use IRAF. So we also use other IRAF tasks like qphot. But thank you for the note :)

**Comment by sosey** [comment] 2016-12-05 17:44
IRAF is not Python 3.0 compatible and there are no current plans for it to be upgraded, as per the information here:  

http://astroconda.readthedocs.io/en/latest/installation.html#legacy-installation-with-iraf 
http://astroconda.readthedocs.io/en/latest/faq.html#why-is-iraf-pyraf-less-functional-under-python-3

You should consider installing an environment with python 2.7 if you still require use of IRAF tools and functionality. 

There are several groups working on replacing IRAF functionality with python tools, so if you are just getting going on your data reduction suite it could be well worth looking at the alternatives. 

You can also suggest items which should be implemented here:  http://astropy.userecho.com/

cheers

**Comment by lupinix** [comment] 2016-12-05 17:53
Using Python 2.7 again is also our current "solution", we made first investigations on migration to 3.5 as compatibility of PyRAF with 3.4 and 3.5 is mentioned here: http://www.stsci.edu/institute/software_hardware/pyraf/current/download

I think I should discuss with our users about the Python replacements. I know most of them as I'm working on Fedora Astronomy stuff (although I still have to package some of them like imexam).

**Comment by cdsontag** [comment] 2016-12-05 17:57
Python replacements are ideal, yes.

But for those using IRAF standard binaries (IRAF tasks from the folks at iraf.net), then yes, PyRAF should enable you to use them in Python 3.*.  Note Megan's warning about STSDAS tasks however.

This current ticket is just a PyRAF bug under that Python 3 scenario, which will be fixed.

**Comment by lupinix** [comment] 2016-12-05 18:01
Yes we are using the IRAF standard binaries

**Comment by cdsontag** [comment] 2016-12-05 18:32
Then you should be good to use PyRAF with them on Python 3.* (for the near term at least), barring the current issue - this ticket.  See also the caveats in the online PyRAF FAQ.

Disclaimer, because we here at STScI have users/processes which still require IRAF tasks, we are continuing (albeit very limited) PyRAF support for now.  Be aware however that that is expected to change in the semi-near future, and we are encouraging all users to move to Python replacements (as @sosey was pointing out).

Of course, you can always submit patches, and/or fork PyRAF on github.

**Comment by cdsontag** [comment] 2016-12-20 15:36
Can someone please post a FITS file which causes this?  I will probably have a chance to work this over the next week or so, and I am not able to reproduce it.  CC @pllim @lupinix

**Comment by pllim** [comment] 2016-12-20 15:45
@cdsontag , the original help call did not come with an attachment, so I don't have any files to give you. My suspicion is that the offending FITS file has special characters in its header.

**Comment by lupinix** [comment] 2016-12-20 19:04
FITS file in attachment, thank you for investigating :)
[Rx_And_Light_001.fits.zip](https://github.com/spacetelescope/stsci.tools/files/664525/Rx_And_Light_001.fits.zip)

**Comment by lupinix** [comment] 2016-12-20 23:29
Way to reproduce:

1.) Use Python 3 PyRAF and stsci.tools (all at latest version), DS9 viewer
2.) display Rx_And_Light_001.fits
3.) imexam
4.) Point to a star in ds9 and type "r" to get a radial plot
5.) You should have the error message I pasted above now

**Comment by lupinix** [comment] 2016-12-20 23:32
Another FITS producing the error, this one was created years ago by a completely different software (Atik Artemis Capture), the Rx And one has been created by KStars (2.7.2) / INDI (1.3.1) if that matters.

[wr134_v_4s_001.fit.zip](https://github.com/spacetelescope/stsci.tools/files/665021/wr134_v_4s_001.fit.zip)

**Comment by cdsontag** [comment] 2016-12-21 15:52
Got this on Rx_And_Light, thanks.  Will likely hit this in the week after Christmas.

>  UnicodeDecodeError: 'ascii' codec can't decode byte 0x95 in position 33: ordinal not in range(128)

**Comment by cdsontag** [comment] 2017-01-04 20:36
All,

Got to the root of this bug today.  It seems that in non-unicode-land (Python 2), the plotting-data bytes passed between imexam and ds9 are not entirely ascii but the s/w is forgiving about it.  So I have changed PyRAF (actually stsci.tools) to work the same way, since we only care about the ASCII part.

The fix is going to require a new version of stsci.tools to download (and I will put out a new pyraf as well, v2.1.14, to mark the occasion), but getting that out to PYPI will take a few days since our guy here is away.

So in the meantime, if anyone wishes to fix their own local install, here is the diff:
```
lib/stsci/tools/irafutils.py:
===================================================================
475c475
<                     if PY3K: snew = snew.decode('ascii')
---
>                     if PY3K: snew = snew.decode('ascii','replace')
502c502
<                 if PY3K: snew = snew.decode('ascii')
---
>                 if PY3K: snew = snew.decode('ascii','replace')
```

for those that want to wait until all is available on pypi for a simple ``pip install``, it will be a little while and I will post here when that is done.

Thanks again for the data @lupinix , and sorry for the delay.

**Comment by pllim** [comment] 2017-01-04 21:23
You can also pip install the latest dev version like this:

```
pip install git+https://github.com/spacetelescope/stsci.tools.git@master
```

**Comment by lupinix** [comment] 2017-01-05 12:19
Thank you very much, will test it soon :)

**Comment by lupinix** [comment] 2017-01-05 13:00
Seems to work fine now 👍

**Comment by pllim** [comment] 2017-01-05 17:06
This fixed is included in 3.4.3.

**Comment by cdsontag** [comment] 2017-01-05 23:01
Great.  This ticket can be closed as soon as stsci.tools 3.4.3 appears on pypi.

**Comment by jhunkeler** [comment] 2017-01-05 23:32
https://pypi.python.org/pypi/stsci.tools/3.4.3

🚀

**Closed** 2017-01-06 04:22 UTC
Labels: bug
